version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - PG_STRING=postgresql://postgres@db:5432/postgres
  db:
    build: ./postgres
    ports:
      - "5432:5432"